### ISSUE TITLE
compile with pyinstaller?

### ISSUE THREAD

**Issue by Nackenschelle** [dustyroo/PUBG-Afk-Credit-Bot#3]
i tried pyinstaller bot after compile to an exe the script wont work anymore.
any solution for me?

**Comment by dustyroo** [comment]
Ill compile it and upload to releases

**Comment by Nackenschelle** [comment]
Traceback (most recent call last):
  File "PUBG.py", line 463, in <module>
    bot_first_start()
  File "PUBG.py", line 459, in bot_first_start
    print('You put '+'~'+resolution_choice+'~'+
TypeError: cannot concatenate 'str' and 'int' objects

any solution?

**Comment by Nackenschelle** [comment]
It also crash if a choose a solution
http://prntscr.com/hbkmvk

**Comment by dustyroo** [comment]
Are you still having an issue I'm trying to fix this.

**Comment by dustyroo** [comment]
Im updating the bot today. If you still have the issue make another ticket.
