### ISSUE TITLE
pick another game mode 

### ISSUE THREAD

**Issue by skyegf** [dustyroo/PUBG-Afk-Credit-Bot#4]
can i pick another game mode ? because squad fpp give less BP
solo seems give more BP 
sorry for bad english , thanks

**Comment by nd4** [comment]
yo skyegf, are you using 1920x1080 ress or 1366x768?

**Comment by skyegf** [comment]
1920x1080

**Comment by skyegf** [comment]
dustyroo answer mee

**Comment by dustyroo** [comment]
Sorry I was busy with my finals. My res is 1920. I will look into the BP aswell

**Comment by dustyroo** [comment]
Old, no response Closed. Feel free to open a new ticket if you still have a problem.
