### ISSUE TITLE
Will the account be banned?

### ISSUE THREAD

**Issue by Caiiiiii** [dustyroo/PUBG-Afk-Credit-Bot#5]
I'm worried about The account will be banned. XD

**Comment by Nackenschelle** [comment]
no risk no fun.

**Comment by Caiiiiii** [comment]
I have a problem, the robot can start the game normally, get down after landing, but after waiting for a few minutes automatically pop-up menu interface, and then remained until the end of the game did not continue to operate in the command indicator to see the robot also stopped .

**Comment by dustyroo** [comment]
Can you please send me a screenshot of what is happening?

**Comment by dustyroo** [comment]
Old, no response Closed. Feel free to open a new ticket if you still have a problem.
